config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
 	namespace :instructor do
    resources :courses, only: [:new, :create, :show]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user

	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!



	def new
		@course = Course.new
	end


	def create
    @course = current_user.courses.create(course_params)
    redirect_to instructor_course_path(@course)
  end


  def show
  	@course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
	<h1>Add a new course</h1>
	<%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1j">
	<h1 class="text-center"><%= @course.title %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skuela</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="flex-content-container">
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <a class="navbar-brand" href="#">Skuela</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
              </ul>
                <ul class="navbar-nav">
                  <% if user_signed_in? %>
                    <li class="nav-item">
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                    </li>
                  <% else %>
                    <li class="nav-item">
                      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                    </li>
                  <% end %>
              </ul>
            </div>
        </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
      </div>
    </div>

  </body>

</html>

app/views/static_pages/index.html.erb
<div class="hero">
	<br />
	<div class="frosty col-10 offset-1 text-center">
		<br />
		<h1>Learn Magic from the Pros</h1>
		<br />
		<h2>I'm an illusionist, Xandrix.</h2>
		<br />
	  <%= link_to 'Learn More', '#', class: 'btn btn-success' %>
	  <br /><br />
	</div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a courses archive of lessons.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Join our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals.</p>
  </div>
</div>